[repos.little_blue]
repo_url = "git@github.com:brandon-braner/little_blue.git"
folder_name = "little_blue"
active = true
main_repo = "master"
develop_repo = "develop"

# These would be run with a setup task
[[repos.little_blue.scripts]]
executable = "pwd"
args = ""
action = "setup"

# These run with the upgrade task
[[repos.little_blue.scripts]]
executable = "pwd"
args = ""
action = "upgrade"

# These will run with all tasks
[[repos.little_blue.scripts]]
executable = "pwd"
args = ""
action = "all"