title = "FieldNation Project Config"
directory = "~/projects/"

[repos]

[repos.mono]
folder_name = "fieldnation"
active = "true"
main_repo = "master"
develop_repo = "develop"

# These run with every task
[[repos.mono.scripts]]
executable = "make"
path = "fake"
action = "upgrade"

[[repos.mono.scripts]]
executable = "make"
path = "fake"
action = "all"