title = "Test Project Config"
directory = "~/projects/"

[repos]
[repos.mono]
folder_name = "test"
active = "true"
main_repo = "master"
develop_repo = "develop"

# These run with the upgrade task
[[repos.mono.scripts]]
executable = "make"
path = "fake"
action = "upgrade"

# These will run with all tasks
[[repos.mono.scripts]]
executable = "make"
path = "fake"
action = "all"